# Generated by Django 4.1.7 on 2023-08-03 20:09

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=myauth.models.avatar_user_directory_path),
        ),
    ]
