# Generated by Django 4.1.7 on 2023-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
