# Generated by Django 4.1.7 on 2023-09-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_article_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
    ]
