# Generated by Django 4.1.7 on 2023-09-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_alter_product_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk'], 'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
    ]
